name: gfwlist2qtx

on:
  workflow_dispatch:
  schedule:
      - cron: '0 1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v1
      - uses: actions/setup-python@v5
        with:
            python-version: '3.9'

      - name: download genpac
        run: pip install -U genpac

      - name: update qtx
        run: genpac --format=qtx --qtx-no-direct --qtx-no-final -o gfwlist.conf

      - name: commit
        run: |
            git config --global user.email 42291428+lemon-sundae@users.noreply.github.com
            git config --global user.name lemon-sundae
            git add .
            git commit -m "update qtx" -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
