name: gfwlist2surge

on:
  workflow_dispatch:
  schedule:
      - cron: '0 1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.9'

      - name: download genpac
        run: pip install -U genpac

      - name: update surge
        run: genpac --format=surge --surge-no-direct --surge-no-final -o gfwlist.conf

      - name: commit
        run: |
            git config --local user.email "42291428+lemon-sundae@users.noreply.github.com"
            git config --local user.name "lemon-sundae"
            git add .
            git commit -m "update surge" -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
